<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{BD98C3E0-FAE7-4EDD-8DA8-7EC933D1EC70}</ProjectGuid>
    <OutputType>WinExe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>ApiSamples</RootNamespace>
    <AssemblyName>ApiSamples</AssemblyName>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
    <RestorePackages>true</RestorePackages>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>bin\Debug\ApiSamples.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>bin\Release\ApiSamples.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>ApiSamples.Program</StartupObject>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>ApiSamples.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ClariusLabs.NuDoc">
      <HintPath>..\packages\NuDoc.0.4.1308.1316\lib\net35\ClariusLabs.NuDoc.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Office.Interop.Excel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c, processorArchitecture=MSIL">
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
    <Reference Include="SolidEdgeContrib, Version=106.0.3.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\packages\SolidEdgeContrib.106.0.3\lib\net40\SolidEdgeContrib.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Extensions.cs" />
    <Compile Include="Forms\RichTextBoxEx.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ListViewEx.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="Samples\FileProperties\DeleteCustomProperties.cs" />
    <Compile Include="Samples\FileProperties\ReportProperties.cs" />
    <Compile Include="Samples\FileProperties\UpdateCustomProperties.cs" />
    <Compile Include="Samples\Helpers.cs" />
    <Compile Include="Samples\Interfaces.cs" />
    <Compile Include="Samples\Revision Manager\ReportFileProperties.cs" />
    <Compile Include="Samples\Revision Manager\StartRevisionManager.cs" />
    <Compile Include="Samples\SolidEdge\Application\ReportGlobalParameters.cs" />
    <Compile Include="Samples\SolidEdge\Application\ReportMaterialLibraryFile.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\AddOccurrenceWithMatrix.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportTubes.cs" />
    <Compile Include="Samples\SolidEdge\Draft\ReportSections.cs" />
    <Compile Include="Samples\SolidEdge\Draft\ReportSheets.cs" />
    <Compile Include="Samples\SolidEdge\Draft\SaveActiveSheetAsEMF.cs" />
    <Compile Include="Samples\SolidEdge\Part\ReportEdgebarFeatures.cs" />
    <Compile Include="Samples\SolidEdge\Part\SaveWindowAsImageUsingBitBlt.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\ReportEdgeBarFeatures.cs" />
    <Compile Include="TextBoxConsole.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="SampleProxy.cs" />
    <Compile Include="Samples\SolidEdge\Application\ReportAddIns.cs" />
    <Compile Include="Samples\SolidEdge\Application\ReportEnvironments.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\CreateNewAssemblyDocument.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\SaveAsJT.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\AddDerivedConfiguration.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\AddNewConfigurationAndApply.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportConfigurations.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\CreateCoffeePot.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\AddOccurrenceByFilename.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\AddOccurrencesWithTransform.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportInterference.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportOccurrences.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportRangeBoxes.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportRelations3d.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\CreateStructuralFrame.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportVariables.cs" />
    <Compile Include="Samples\SolidEdge\Assembly\SaveWindowAsImage.cs" />
    <Compile Include="Samples\Constants.cs" />
    <Compile Include="Samples\OleMessageFilter.cs" />
    <Compile Include="Samples\SolidEdge\Constants.cs" />
    <Compile Include="Samples\SolidEdge\Extensions.cs" />
    <Compile Include="Samples\SolidEdge\Helpers.cs" />
    <Compile Include="Samples\SolidEdge\Part\PartHelper.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SheetMetalHelper.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CreateBalloon.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CreateCircle2dByCenterRadius.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CreateCirclesWithDimensions.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CreateLineWithDimensions.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CreatePartViewWithDimensions.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CreateDraftDocument.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CreateAssemblyDrawingView.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CreatePartDrawingView.cs" />
    <Compile Include="Samples\SolidEdge\Draft\ConvertDrawingViewsTo2D.cs" />
    <Compile Include="Samples\SolidEdge\Draft\UpdateAllDrawingViewsInWorkingSection.cs" />
    <Compile Include="Samples\SolidEdge\Draft\DrawPolygon.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CreateLeader.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CreateLinesIn45DegreeIncrements.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CopyPartsListsToClipboard.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CopyPartsListsToClipboardAndPasteIntoExcel.cs" />
    <Compile Include="Samples\SolidEdge\Draft\WritePartsListsToExcel.cs" />
    <Compile Include="Samples\SolidEdge\Draft\AddSheet.cs" />
    <Compile Include="Samples\SolidEdge\Draft\SaveWindowAsImage.cs" />
    <Compile Include="Samples\SolidEdge\Draft\CreateTextBoxWithCoordinateValuesAsText.cs" />
    <Compile Include="Samples\SolidEdge\Draft\ReportVariables.cs" />
    <Compile Include="MainForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="MainForm.Designer.cs">
      <DependentUpon>MainForm.cs</DependentUpon>
    </Compile>
    <Compile Include="Samples\SolidEdge\Part\ReportBodyFacetData.cs" />
    <Compile Include="Samples\SolidEdge\Part\ReportBodyRange.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateBsplineCurves2dByPoints.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateChamferByAddEqualSetback.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateChamferByAddSetbackAngle.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateChamferByAddUnequalSetback.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateCircle2dByCenterRadius.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreatePolygon.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateExtrudedSurfaceByCircles2d.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateFaceRotateByGeometry.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateFaceRotateByPoints.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateFamilyMemberSuppressedFeature.cs" />
    <Compile Include="Samples\SolidEdge\Part\ReportFamilyMembers.cs" />
    <Compile Include="Samples\SolidEdge\Part\MoveAllOrderedFeaturesToSynchronous.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateHoleWithUserDefinedPattern.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateSimpleLoftedCutout.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateThickenFeatures.cs" />
    <Compile Include="Samples\SolidEdge\Part\HealAndOptimizeBody.cs" />
    <Compile Include="Samples\SolidEdge\Part\RecomputeModel.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreatePartDocument.cs" />
    <Compile Include="Samples\SolidEdge\Part\SaveAsJT.cs" />
    <Compile Include="Samples\SolidEdge\Part\ComputePhysicalPropertiesAndReport.cs" />
    <Compile Include="Samples\SolidEdge\Part\GetPhysicalPropertiesAndReport.cs" />
    <Compile Include="Samples\SolidEdge\Part\PlaceFeatureLibrary.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateFiniteExtrudedProtrusion.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateFiniteRevolvedProtrusion.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateSweptProtrusion.cs" />
    <Compile Include="Samples\SolidEdge\Part\Recompute.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateRoundWithMultipleEdges.cs" />
    <Compile Include="Samples\SolidEdge\Part\SetModelingModeToOrdered.cs" />
    <Compile Include="Samples\SolidEdge\Part\SetModelingModeToSynchronous.cs" />
    <Compile Include="Samples\SolidEdge\Part\CreateSlot.cs" />
    <Compile Include="Samples\SolidEdge\Part\ReportVariables.cs" />
    <Compile Include="Samples\SolidEdge\Part\SaveWindowAsImage.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateDimple.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateEtch.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateExtrudedCutout.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateFamilyMemberWithSuppressedFeature.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\ReportFamilyMembers.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\MoveAllOrderedFeaturesToSynchronous.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateHoleWithUserDefinedPattern.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateLoftedFlange.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\HealAndOptimizeBody.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\RecomputeModel.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SaveAsFlatDXF.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\ComputePhysicalPropertiesAndReport.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\GetPhysicalPropertiesAndReport.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\PlaceFeatureLibrary.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\Recompute.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SetModelingModeToOrdered.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SetModelingModeToSynchronous.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateSheetMetalDocument.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SaveAsJT.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateSlot.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateBaseTab.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateBaseTabByCircle.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\ReportVariables.cs" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SaveWindowAsImage.cs" />
    <Compile Include="Samples\SolidEdge\Application\ReportGlobalSystemInformation.cs" />
    <Compile Include="Samples\SolidEdge\Application\StartSolidEdge.cs" />
    <Compile Include="Samples\SolidEdge\Application\CloseAllDocuments.cs" />
    <Compile Include="Samples\SolidEdge\Application\CloseAllDocumentsSilent.cs" />
    <Compile Include="Samples\SolidEdge\Application\CreateAssemblyDocument.cs" />
    <Compile Include="Samples\SolidEdge\Application\CreateDraftDocument.cs" />
    <Compile Include="Samples\SolidEdge\Application\CreatePartDocument.cs" />
    <Compile Include="Samples\SolidEdge\Application\CreateNewSheetMetalDocument.cs" />
    <Compile Include="Samples\SolidEdge\Application\ReportInstallData.cs" />
    <Compile Include="Samples\SolidEdge\Application\ReportMaterials.cs" />
    <Compile Include="Samples\SolidEdge\Application\AddCustomProperties.cs" />
    <Compile Include="Samples\SolidEdge\Application\ReportProperties.cs" />
    <Compile Include="Samples\SolidEdge\Application\AddObjectsToSelectSet.cs" />
    <Compile Include="Samples\SolidEdge\Application\ClearSelectSet.cs" />
    <Compile Include="Samples\SolidEdge\Application\ReportActiveSelectSet.cs" />
    <EmbeddedResource Include="MainForm.resx">
      <DependentUpon>MainForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <SubType>Designer</SubType>
      <CustomToolNamespace>ApiSamples</CustomToolNamespace>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <None Include="packages.config" />
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
      <CustomToolNamespace>ApiSamples</CustomToolNamespace>
    </None>
    <Compile Include="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
    <None Include="Samples\Notes\SaveAsImage.docx" />
  </ItemGroup>
  <ItemGroup />
  <ItemGroup>
    <Content Include="ApiSamples.ico" />
    <None Include="Media\Breakpoint_16x16.png" />
    <None Include="Media\FolderOpen_16x16.png" />
    <None Include="Media\FolderClosed_16x16.png" />
    <None Include="Media\Method_16x16.png" />
    <None Include="Media\Run_16x16.png" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="..\packages\SolidEdgeContrib.106.0.3\build\net40\SolidEdgeContrib.targets" Condition="Exists('..\packages\SolidEdgeContrib.106.0.3\build\net40\SolidEdgeContrib.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\SolidEdgeContrib.106.0.3\build\net40\SolidEdgeContrib.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\SolidEdgeContrib.106.0.3\build\net40\SolidEdgeContrib.targets'))" />
  </Target>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>