<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{BD98C3E0-FAE7-4EDD-8DA8-7EC933D1EC70}</ProjectGuid>
    <OutputType>WinExe</OutputType>
    <RootNamespace>
    </RootNamespace>
    <AssemblyName>ApiSamples</AssemblyName>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
    <RestorePackages>true</RestorePackages>
    <OptionExplicit>On</OptionExplicit>
    <OptionCompare>Binary</OptionCompare>
    <OptionStrict>Off</OptionStrict>
    <OptionInfer>On</OptionInfer>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <ErrorReport>prompt</ErrorReport>
    <DocumentationFile>bin\Debug\ApiSamples.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineDebug>false</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <ErrorReport>prompt</ErrorReport>
    <DocumentationFile>bin\Release\ApiSamples.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>ApiSamples.Program</StartupObject>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>ApiSamples.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ClariusLabs.NuDoc">
      <HintPath>..\packages\NuDoc.0.4.1308.1316\lib\net35\ClariusLabs.NuDoc.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Office.Interop.Excel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c, processorArchitecture=MSIL">
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
    <Reference Include="SolidEdgeContrib, Version=106.0.3.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\packages\SolidEdgeContrib.106.0.3\lib\net40\SolidEdgeContrib.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="Microsoft.VisualBasic" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.Collections" />
    <Import Include="System.Diagnostics" />
    <Import Include="System.Linq" />
    <Import Include="System.Xml.Linq" />
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
    <Import Include="System" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Extensions.vb" />
    <Compile Include="Forms\RichTextBoxEx.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="ListViewEx.vb">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="Samples\FileProperties\DeleteCustomProperties.vb" />
    <Compile Include="Samples\FileProperties\ReportProperties.vb" />
    <Compile Include="Samples\FileProperties\UpdateCustomProperties.vb" />
    <Compile Include="Samples\Helpers.vb" />
    <Compile Include="Samples\Interfaces.vb" />
    <Compile Include="Samples\Revision Manager\ReportFileProperties.vb" />
    <Compile Include="Samples\Revision Manager\StartRevisionManager.vb" />
    <Compile Include="Samples\SolidEdge\Application\ReportGlobalParameters.vb" />
    <Compile Include="Samples\SolidEdge\Application\ReportMaterialLibraryFile.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\AddOccurrenceWithMatrix.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportTubes.vb" />
    <Compile Include="Samples\SolidEdge\Draft\ReportSections.vb" />
    <Compile Include="Samples\SolidEdge\Draft\ReportSheets.vb" />
    <Compile Include="Samples\SolidEdge\Draft\SaveActiveSheetAsEMF.vb" />
    <Compile Include="Samples\SolidEdge\Part\ReportEdgebarFeatures.vb" />
    <Compile Include="Samples\SolidEdge\Part\SaveWindowAsImageUsingBitBlt.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\ReportEdgeBarFeatures.vb" />
    <Compile Include="TextBoxConsole.vb" />
    <Compile Include="My Project\Resources.Designer.vb">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="SampleProxy.vb" />
    <Compile Include="Samples\SolidEdge\Application\ReportAddIns.vb" />
    <Compile Include="Samples\SolidEdge\Application\ReportEnvironments.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\CreateNewAssemblyDocument.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\SaveAsJT.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\AddDerivedConfiguration.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\AddNewConfigurationAndApply.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportConfigurations.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\CreateCoffeePot.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\AddOccurrenceByFilename.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\AddOccurrencesWithTransform.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportInterference.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportOccurrences.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportRangeBoxes.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportRelations3d.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\CreateStructuralFrame.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\ReportVariables.vb" />
    <Compile Include="Samples\SolidEdge\Assembly\SaveWindowAsImage.vb" />
    <Compile Include="Samples\Constants.vb" />
    <Compile Include="Samples\OleMessageFilter.vb" />
    <Compile Include="Samples\SolidEdge\Constants.vb" />
    <Compile Include="Samples\SolidEdge\Extensions.vb" />
    <Compile Include="Samples\SolidEdge\Helpers.vb" />
    <Compile Include="Samples\SolidEdge\Part\PartHelper.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SheetMetalHelper.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CreateBalloon.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CreateCircle2dByCenterRadius.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CreateCirclesWithDimensions.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CreateLineWithDimensions.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CreatePartViewWithDimensions.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CreateDraftDocument.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CreateAssemblyDrawingView.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CreatePartDrawingView.vb" />
    <Compile Include="Samples\SolidEdge\Draft\ConvertDrawingViewsTo2D.vb" />
    <Compile Include="Samples\SolidEdge\Draft\UpdateAllDrawingViewsInWorkingSection.vb" />
    <Compile Include="Samples\SolidEdge\Draft\DrawPolygon.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CreateLeader.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CreateLinesIn45DegreeIncrements.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CopyPartsListsToClipboard.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CopyPartsListsToClipboardAndPasteIntoExcel.vb" />
    <Compile Include="Samples\SolidEdge\Draft\WritePartsListsToExcel.vb" />
    <Compile Include="Samples\SolidEdge\Draft\AddSheet.vb" />
    <Compile Include="Samples\SolidEdge\Draft\SaveWindowAsImage.vb" />
    <Compile Include="Samples\SolidEdge\Draft\CreateTextBoxWithCoordinateValuesAsText.vb" />
    <Compile Include="Samples\SolidEdge\Draft\ReportVariables.vb" />
    <Compile Include="MainForm.vb">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="MainForm.Designer.vb">
      <DependentUpon>MainForm.vb</DependentUpon>
    </Compile>
    <Compile Include="Samples\SolidEdge\Part\ReportBodyFacetData.vb" />
    <Compile Include="Samples\SolidEdge\Part\ReportBodyRange.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateBsplineCurves2dByPoints.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateChamferByAddEqualSetback.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateChamferByAddSetbackAngle.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateChamferByAddUnequalSetback.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateCircle2dByCenterRadius.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreatePolygon.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateExtrudedSurfaceByCircles2d.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateFaceRotateByGeometry.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateFaceRotateByPoints.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateFamilyMemberSuppressedFeature.vb" />
    <Compile Include="Samples\SolidEdge\Part\ReportFamilyMembers.vb" />
    <Compile Include="Samples\SolidEdge\Part\MoveAllOrderedFeaturesToSynchronous.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateHoleWithUserDefinedPattern.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateSimpleLoftedCutout.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateThickenFeatures.vb" />
    <Compile Include="Samples\SolidEdge\Part\HealAndOptimizeBody.vb" />
    <Compile Include="Samples\SolidEdge\Part\RecomputeModel.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreatePartDocument.vb" />
    <Compile Include="Samples\SolidEdge\Part\SaveAsJT.vb" />
    <Compile Include="Samples\SolidEdge\Part\ComputePhysicalPropertiesAndReport.vb" />
    <Compile Include="Samples\SolidEdge\Part\GetPhysicalPropertiesAndReport.vb" />
    <Compile Include="Samples\SolidEdge\Part\PlaceFeatureLibrary.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateFiniteExtrudedProtrusion.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateFiniteRevolvedProtrusion.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateSweptProtrusion.vb" />
    <Compile Include="Samples\SolidEdge\Part\Recompute.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateRoundWithMultipleEdges.vb" />
    <Compile Include="Samples\SolidEdge\Part\SetModelingModeToOrdered.vb" />
    <Compile Include="Samples\SolidEdge\Part\SetModelingModeToSynchronous.vb" />
    <Compile Include="Samples\SolidEdge\Part\CreateSlot.vb" />
    <Compile Include="Samples\SolidEdge\Part\ReportVariables.vb" />
    <Compile Include="Samples\SolidEdge\Part\SaveWindowAsImage.vb" />
    <Compile Include="Program.vb" />
    <Compile Include="My Project\AssemblyInfo.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateDimple.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateEtch.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateExtrudedCutout.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateFamilyMemberWithSuppressedFeature.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\ReportFamilyMembers.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\MoveAllOrderedFeaturesToSynchronous.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateHoleWithUserDefinedPattern.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateLoftedFlange.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\HealAndOptimizeBody.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\RecomputeModel.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SaveAsFlatDXF.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\ComputePhysicalPropertiesAndReport.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\GetPhysicalPropertiesAndReport.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\PlaceFeatureLibrary.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\Recompute.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SetModelingModeToOrdered.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SetModelingModeToSynchronous.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateSheetMetalDocument.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SaveAsJT.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateSlot.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateBaseTab.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\CreateBaseTabByCircle.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\ReportVariables.vb" />
    <Compile Include="Samples\SolidEdge\SheetMetal\SaveWindowAsImage.vb" />
    <Compile Include="Samples\SolidEdge\Application\ReportGlobalSystemInformation.vb" />
    <Compile Include="Samples\SolidEdge\Application\StartSolidEdge.vb" />
    <Compile Include="Samples\SolidEdge\Application\CloseAllDocuments.vb" />
    <Compile Include="Samples\SolidEdge\Application\CloseAllDocumentsSilent.vb" />
    <Compile Include="Samples\SolidEdge\Application\CreateAssemblyDocument.vb" />
    <Compile Include="Samples\SolidEdge\Application\CreateDraftDocument.vb" />
    <Compile Include="Samples\SolidEdge\Application\CreatePartDocument.vb" />
    <Compile Include="Samples\SolidEdge\Application\CreateNewSheetMetalDocument.vb" />
    <Compile Include="Samples\SolidEdge\Application\ReportInstallData.vb" />
    <Compile Include="Samples\SolidEdge\Application\ReportMaterials.vb" />
    <Compile Include="Samples\SolidEdge\Application\AddCustomProperties.vb" />
    <Compile Include="Samples\SolidEdge\Application\ReportProperties.vb" />
    <Compile Include="Samples\SolidEdge\Application\AddObjectsToSelectSet.vb" />
    <Compile Include="Samples\SolidEdge\Application\ClearSelectSet.vb" />
    <Compile Include="Samples\SolidEdge\Application\ReportActiveSelectSet.vb" />
    <EmbeddedResource Include="MainForm.resx">
      <DependentUpon>MainForm.vb</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="My Project\Resources.resx">
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <SubType>Designer</SubType>
      <CustomToolNamespace>ApiSamples</CustomToolNamespace>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
    </EmbeddedResource>
    <None Include="packages.config" />
    <None Include="My Project\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.vb</LastGenOutput>
      <CustomToolNamespace>ApiSamples</CustomToolNamespace>
    </None>
    <Compile Include="My Project\Settings.Designer.vb">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
    <None Include="Samples\Notes\SaveAsImage.docx" />
  </ItemGroup>
  <ItemGroup />
  <ItemGroup>
    <Content Include="ApiSamples.ico" />
    <None Include="Media\Breakpoint_16x16.png" />
    <None Include="Media\FolderOpen_16x16.png" />
    <None Include="Media\FolderClosed_16x16.png" />
    <None Include="Media\Method_16x16.png" />
    <None Include="Media\Run_16x16.png" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.VisualBasic.targets" />
  <Import Project="..\packages\SolidEdgeContrib.106.0.3\build\net40\SolidEdgeContrib.targets" Condition="Exists('..\packages\SolidEdgeContrib.106.0.3\build\net40\SolidEdgeContrib.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\SolidEdgeContrib.106.0.3\build\net40\SolidEdgeContrib.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\SolidEdgeContrib.106.0.3\build\net40\SolidEdgeContrib.targets'))" />
  </Target>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it.
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>