using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ApiSamples.Samples.SolidEdge
{
    static partial class ProgId
    {
        public const string Application = "SolidEdge.Application";
        public const string AssemblyDocument = "SolidEdge.AssemblyDocument";
        public const string ConfigFileExtension = "SolidEdge.ConfigFileExtension";
        public const string FamilyOfAssembliesDocument = "SolidEdge.FamilyOfAssembliesDocument";
        public const string SynchronousAssemblyDocument = "SolidEdge.DMAssemblyDocument";
        public const string DraftDocument = "SolidEdge.DraftDocument";
        public const string MarkupDocument = "SmartView.SEMarkupDocument";
        public const string PartDocument = "SolidEdge.PartDocument";
        public const string SheetMetalDocument = "SolidEdge.SheetMetalDocument";
        public const string SynchronousPartDocument = "SolidEdge.DMPartDocument";
        public const string SynchronousSheetMetalDocument = "SolidEdge.DMSheetMetalDocument";
        public const string WeldmentDocument = "SolidEdge.WeldmentDocument";
    }
}
